export const MESSAGE_SEND_REQUEST = 'MESSAGE_SEND_REQUEST'
export const MESSAGE_SEND_SUCCESS = 'MESSAGE_SEND_SUCCESS'
export const MESSAGE_SEND_FAIL = 'MESSAGE_SEND_FAIL'

export const MESSAGE_RESET = 'MESSAGE_RESET'
export const MESSAGE_CHANGE = 'MESSAGE_CHANGE'
